### ISSUE TITLE
Instrument non-UI telemetry probes

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/price-wise#158]
This issue covers instrumenting all non-UI probes. The probes list was generated from METRICS.md (#134).

#### Events:
- [x] `detect_price_change`
- [x] `badge_toolbar_button`
- [x] `send_notification`
  - [x] [Add an additional key](https://github.com/mozilla/price-scout/issues/127#issuecomment-432350950) to probe and METRICS.md for `price_last_high`
  - [x] Update the `open_external_page` for `element` of `'system_notification'` to add this key and update the doc.
- [x] `attempt_extraction` (see discussion in #125)
- [x] `complete_extraction` (see discussion in #125)
